// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/accountalloweduser"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountAllowedUserDelete is the builder for deleting a AccountAllowedUser entity.
type AccountAllowedUserDelete struct {
	config
	hooks    []Hook
	mutation *AccountAllowedUserMutation
}

// Where appends a list predicates to the AccountAllowedUserDelete builder.
func (_d *AccountAllowedUserDelete) Where(ps ...predicate.AccountAllowedUser) *AccountAllowedUserDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountAllowedUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountAllowedUserDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountAllowedUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountalloweduser.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountAllowedUserDeleteOne is the builder for deleting a single AccountAllowedUser entity.
type AccountAllowedUserDeleteOne struct {
	_d *AccountAllowedUserDelete
}

// Where appends a list predicates to the AccountAllowedUserDelete builder.
func (_d *AccountAllowedUserDeleteOne) Where(ps ...predicate.AccountAllowedUser) *AccountAllowedUserDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountAllowedUserDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountalloweduser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountAllowedUserDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
