// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountalloweduser"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountAllowedUserCreate is the builder for creating a AccountAllowedUser entity.
type AccountAllowedUserCreate struct {
	config
	mutation *AccountAllowedUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountAllowedUserCreate) SetAccountID(v int64) *AccountAllowedUserCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountAllowedUserCreate) SetUserID(v int64) *AccountAllowedUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountAllowedUserCreate) SetCreatedAt(v time.Time) *AccountAllowedUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountAllowedUserCreate) SetNillableCreatedAt(v *time.Time) *AccountAllowedUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountAllowedUserCreate) SetAccount(v *Account) *AccountAllowedUserCreate {
	return _c.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountAllowedUserCreate) SetUser(v *User) *AccountAllowedUserCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountAllowedUserMutation object of the builder.
func (_c *AccountAllowedUserCreate) Mutation() *AccountAllowedUserMutation {
	return _c.mutation
}

// Save creates the AccountAllowedUser in the database.
func (_c *AccountAllowedUserCreate) Save(ctx context.Context) (*AccountAllowedUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountAllowedUserCreate) SaveX(ctx context.Context) *AccountAllowedUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountAllowedUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountAllowedUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountAllowedUserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountalloweduser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountAllowedUserCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountAllowedUser.account_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AccountAllowedUser.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountAllowedUser.created_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountAllowedUser.account"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccountAllowedUser.user"`)}
	}
	return nil
}

func (_c *AccountAllowedUserCreate) sqlSave(ctx context.Context) (*AccountAllowedUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *AccountAllowedUserCreate) createSpec() (*AccountAllowedUser, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountAllowedUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountalloweduser.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountalloweduser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.AccountTable,
			Columns: []string{accountalloweduser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.UserTable,
			Columns: []string{accountalloweduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountAllowedUser.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountAllowedUserUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountAllowedUserCreate) OnConflict(opts ...sql.ConflictOption) *AccountAllowedUserUpsertOne {
	_c.conflict = opts
	return &AccountAllowedUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountAllowedUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountAllowedUserCreate) OnConflictColumns(columns ...string) *AccountAllowedUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountAllowedUserUpsertOne{
		create: _c,
	}
}

type (
	// AccountAllowedUserUpsertOne is the builder for "upsert"-ing
	//  one AccountAllowedUser node.
	AccountAllowedUserUpsertOne struct {
		create *AccountAllowedUserCreate
	}

	// AccountAllowedUserUpsert is the "OnConflict" setter.
	AccountAllowedUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountAllowedUserUpsert) SetAccountID(v int64) *AccountAllowedUserUpsert {
	u.Set(accountalloweduser.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountAllowedUserUpsert) UpdateAccountID() *AccountAllowedUserUpsert {
	u.SetExcluded(accountalloweduser.FieldAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountAllowedUserUpsert) SetUserID(v int64) *AccountAllowedUserUpsert {
	u.Set(accountalloweduser.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountAllowedUserUpsert) UpdateUserID() *AccountAllowedUserUpsert {
	u.SetExcluded(accountalloweduser.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountAllowedUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountAllowedUserUpsertOne) UpdateNewValues() *AccountAllowedUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountalloweduser.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountAllowedUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountAllowedUserUpsertOne) Ignore() *AccountAllowedUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountAllowedUserUpsertOne) DoNothing() *AccountAllowedUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountAllowedUserCreate.OnConflict
// documentation for more info.
func (u *AccountAllowedUserUpsertOne) Update(set func(*AccountAllowedUserUpsert)) *AccountAllowedUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountAllowedUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountAllowedUserUpsertOne) SetAccountID(v int64) *AccountAllowedUserUpsertOne {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountAllowedUserUpsertOne) UpdateAccountID() *AccountAllowedUserUpsertOne {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountAllowedUserUpsertOne) SetUserID(v int64) *AccountAllowedUserUpsertOne {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountAllowedUserUpsertOne) UpdateUserID() *AccountAllowedUserUpsertOne {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *AccountAllowedUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountAllowedUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountAllowedUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// AccountAllowedUserCreateBulk is the builder for creating many AccountAllowedUser entities in bulk.
type AccountAllowedUserCreateBulk struct {
	config
	err      error
	builders []*AccountAllowedUserCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountAllowedUser entities in the database.
func (_c *AccountAllowedUserCreateBulk) Save(ctx context.Context) ([]*AccountAllowedUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountAllowedUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountAllowedUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountAllowedUserCreateBulk) SaveX(ctx context.Context) []*AccountAllowedUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountAllowedUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountAllowedUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountAllowedUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountAllowedUserUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountAllowedUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountAllowedUserUpsertBulk {
	_c.conflict = opts
	return &AccountAllowedUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountAllowedUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountAllowedUserCreateBulk) OnConflictColumns(columns ...string) *AccountAllowedUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountAllowedUserUpsertBulk{
		create: _c,
	}
}

// AccountAllowedUserUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountAllowedUser nodes.
type AccountAllowedUserUpsertBulk struct {
	create *AccountAllowedUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountAllowedUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountAllowedUserUpsertBulk) UpdateNewValues() *AccountAllowedUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountalloweduser.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountAllowedUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountAllowedUserUpsertBulk) Ignore() *AccountAllowedUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountAllowedUserUpsertBulk) DoNothing() *AccountAllowedUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountAllowedUserCreateBulk.OnConflict
// documentation for more info.
func (u *AccountAllowedUserUpsertBulk) Update(set func(*AccountAllowedUserUpsert)) *AccountAllowedUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountAllowedUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountAllowedUserUpsertBulk) SetAccountID(v int64) *AccountAllowedUserUpsertBulk {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountAllowedUserUpsertBulk) UpdateAccountID() *AccountAllowedUserUpsertBulk {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountAllowedUserUpsertBulk) SetUserID(v int64) *AccountAllowedUserUpsertBulk {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountAllowedUserUpsertBulk) UpdateUserID() *AccountAllowedUserUpsertBulk {
	return u.Update(func(s *AccountAllowedUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *AccountAllowedUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountAllowedUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountAllowedUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountAllowedUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
