// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountalloweduser"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountAllowedUserUpdate is the builder for updating AccountAllowedUser entities.
type AccountAllowedUserUpdate struct {
	config
	hooks    []Hook
	mutation *AccountAllowedUserMutation
}

// Where appends a list predicates to the AccountAllowedUserUpdate builder.
func (_u *AccountAllowedUserUpdate) Where(ps ...predicate.AccountAllowedUser) *AccountAllowedUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountAllowedUserUpdate) SetAccountID(v int64) *AccountAllowedUserUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountAllowedUserUpdate) SetNillableAccountID(v *int64) *AccountAllowedUserUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountAllowedUserUpdate) SetUserID(v int64) *AccountAllowedUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountAllowedUserUpdate) SetNillableUserID(v *int64) *AccountAllowedUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountAllowedUserUpdate) SetAccount(v *Account) *AccountAllowedUserUpdate {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountAllowedUserUpdate) SetUser(v *User) *AccountAllowedUserUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountAllowedUserMutation object of the builder.
func (_u *AccountAllowedUserUpdate) Mutation() *AccountAllowedUserMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountAllowedUserUpdate) ClearAccount() *AccountAllowedUserUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountAllowedUserUpdate) ClearUser() *AccountAllowedUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountAllowedUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountAllowedUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountAllowedUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountAllowedUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountAllowedUserUpdate) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountAllowedUser.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountAllowedUser.user"`)
	}
	return nil
}

func (_u *AccountAllowedUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountalloweduser.Table, accountalloweduser.Columns, sqlgraph.NewFieldSpec(accountalloweduser.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountalloweduser.FieldUserID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.AccountTable,
			Columns: []string{accountalloweduser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.AccountTable,
			Columns: []string{accountalloweduser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.UserTable,
			Columns: []string{accountalloweduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.UserTable,
			Columns: []string{accountalloweduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountalloweduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountAllowedUserUpdateOne is the builder for updating a single AccountAllowedUser entity.
type AccountAllowedUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountAllowedUserMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountAllowedUserUpdateOne) SetAccountID(v int64) *AccountAllowedUserUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountAllowedUserUpdateOne) SetNillableAccountID(v *int64) *AccountAllowedUserUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountAllowedUserUpdateOne) SetUserID(v int64) *AccountAllowedUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountAllowedUserUpdateOne) SetNillableUserID(v *int64) *AccountAllowedUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountAllowedUserUpdateOne) SetAccount(v *Account) *AccountAllowedUserUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountAllowedUserUpdateOne) SetUser(v *User) *AccountAllowedUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountAllowedUserMutation object of the builder.
func (_u *AccountAllowedUserUpdateOne) Mutation() *AccountAllowedUserMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountAllowedUserUpdateOne) ClearAccount() *AccountAllowedUserUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountAllowedUserUpdateOne) ClearUser() *AccountAllowedUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AccountAllowedUserUpdate builder.
func (_u *AccountAllowedUserUpdateOne) Where(ps ...predicate.AccountAllowedUser) *AccountAllowedUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountAllowedUserUpdateOne) Select(field string, fields ...string) *AccountAllowedUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountAllowedUser entity.
func (_u *AccountAllowedUserUpdateOne) Save(ctx context.Context) (*AccountAllowedUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountAllowedUserUpdateOne) SaveX(ctx context.Context) *AccountAllowedUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountAllowedUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountAllowedUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountAllowedUserUpdateOne) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountAllowedUser.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountAllowedUser.user"`)
	}
	return nil
}

func (_u *AccountAllowedUserUpdateOne) sqlSave(ctx context.Context) (_node *AccountAllowedUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountalloweduser.Table, accountalloweduser.Columns, sqlgraph.NewFieldSpec(accountalloweduser.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountalloweduser.FieldUserID, field.TypeInt64))
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "AccountAllowedUser.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "AccountAllowedUser.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !accountalloweduser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.AccountTable,
			Columns: []string{accountalloweduser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.AccountTable,
			Columns: []string{accountalloweduser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.UserTable,
			Columns: []string{accountalloweduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountalloweduser.UserTable,
			Columns: []string{accountalloweduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountAllowedUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountalloweduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
