// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountalloweduser"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountAllowedUser is the model entity for the AccountAllowedUser schema.
type AccountAllowedUser struct {
	config `json:"-"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountAllowedUserQuery when eager-loading is set.
	Edges        AccountAllowedUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountAllowedUserEdges holds the relations/edges for other nodes in the graph.
type AccountAllowedUserEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountAllowedUserEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountAllowedUserEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountAllowedUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountalloweduser.FieldAccountID, accountalloweduser.FieldUserID:
			values[i] = new(sql.NullInt64)
		case accountalloweduser.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountAllowedUser fields.
func (_m *AccountAllowedUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountalloweduser.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountalloweduser.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case accountalloweduser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountAllowedUser.
// This includes values selected through modifiers, order, etc.
func (_m *AccountAllowedUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountAllowedUser entity.
func (_m *AccountAllowedUser) QueryAccount() *AccountQuery {
	return NewAccountAllowedUserClient(_m.config).QueryAccount(_m)
}

// QueryUser queries the "user" edge of the AccountAllowedUser entity.
func (_m *AccountAllowedUser) QueryUser() *UserQuery {
	return NewAccountAllowedUserClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this AccountAllowedUser.
// Note that you need to call AccountAllowedUser.Unwrap() before calling this method if this AccountAllowedUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountAllowedUser) Update() *AccountAllowedUserUpdateOne {
	return NewAccountAllowedUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountAllowedUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountAllowedUser) Unwrap() *AccountAllowedUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountAllowedUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountAllowedUser) String() string {
	var builder strings.Builder
	builder.WriteString("AccountAllowedUser(")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountAllowedUsers is a parsable slice of AccountAllowedUser.
type AccountAllowedUsers []*AccountAllowedUser
